version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=MySecureP@ss1
      - DB_NAME=social_app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySecureP@ss1
      MYSQL_DATABASE: social_app
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
